### ISSUE TITLE
Issues in Mac running "native" Docker

### ISSUE THREAD

**Issue by jameszh** [test-kitchen/kitchen-docker#266]
already specify
sudo: false
running kitchen-docker (2.6.0)

$ bundle exec kitchen test
-----> Starting Kitchen (v1.16.0)
-----> Cleaning up any prior instances of <default-ubuntu>
-----> Destroying <default-ubuntu>...
       Finished destroying <default-ubuntu> (0m0.00s).
-----> Testing <default-ubuntu>
-----> Creating <default-ubuntu>...
       unable to prepare context: The Dockerfile (/..path..to/Dockerfile-kitchen20170426-58103-1u8s9ms) must be within the build context (.)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of docker -H unix:///var/run/docker.sock build -f /..path..to/Dockerfile-kitchen20170426-58103-1u8s9ms . ----
STDOUT:
STDERR: unable to prepare context: The Dockerfile (/..path..to/Dockerfile-kitchen20170426-58103-1u8s9ms) must be within the build context (.)
---- End output of docker -H unix:///var/run/docker.sock build -f /..path..to/Dockerfile-kitchen20170426-58103-1u8s9ms . ----
Ran docker -H unix:///var/run/docker.sock build -f /..path..to/Dockerfile-kitchen20170426-58103-1u8s9ms . returned 1] on default-ubuntu
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by peterabbott** [comment]
From the error message it looks like you are trying to use a custom Dockerfile, is the location right? 

What does the .kitchen.yml file look like ?

**Comment by jameszh** [comment]
Here it is:

---
driver:
  name: docker
  use_sudo: false
  socket: unix:///var/run/docker.sock
provisioner:
  name: ansible_playbook
  playbook: playbook.yml
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: true
platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:14.04
      platform: ubuntu
suites:
  - name: default
verifier:
  ruby_bindir: '/usr/bin'

**Comment by peterabbott** [comment]
I copied the kitchen file and test kitchen is able to create the container. 

Silly question is if Docker is running? From the command line can you access docker daemon without test kitchen, does a simple ` docker ps ` work? 

Otherwise, usual suspect is the format of the YAML, it can be picky about spaces?? 

If you are running via bundler could there be a bundler issue that has not finished properly or conflicting gems?

**Comment by jameszh** [comment]
yes docker is working:

$ docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                                          NAMES
0cdfde0b657a           graphite   "/sbin/my_init"     3 months ago        Up 39 seconds       0.0.0.0:2003->2003/tcp, 0.0.0.0:8080->80/tcp   graphite


and the yaml, checked with http://www.yamllint.com/ <http://www.yamllint.com/> is valid

Here is the Gemfile:

source 'https://rubygems.org'
gem 'test-kitchen', '~> 1.6'
gem 'kitchen-ansible', '~> 0.46'
gem 'kitchen-vagrant', '~> 1.1.0'
gem 'serverspec', '~> 2.36'
gem 'kitchen-docker', '~> 2.6’


with or w/o bundler, the same result, running ruby 2.3.1

**Comment by peterabbott** [comment]
The one only difference I see is my quick test was with ruby 2.1.5 and Docker 17.03.1-ce-mac5

Only other thought is there is a symlink stuffing things up, but that kitchen config was working for my setup. Sorry.

**Comment by jameszh** [comment]
it’s bizarre, I move  the folder  to ~/tmp, it worked, then I moved it back to original location, it worked too.  I can’t explain.
my  docker version: Docker version 17.05.0-ce-rc1, build 2878a85

**Comment by nilroy** [comment]
@jameszh I was also facing the same issue. But somehow I was able to discover the reason. It was because of case insensitivity of mac OS. I had a folder named GIT (all in caps)  in my home directory where I had my cookbook folder. Now if I cd to ***git/\<My cookbook directory\>*** and run the test it fails with the same error. But if I cd to ***GIT/\<My cookbook directory\>*** and run the test it goes through. So the bottom line is we need to follow the exact directory name (don't rely on mac's case insensitivity). I hope it helps.

**Comment by jameszh** [comment]
thanks, you solved my puzzle.
