### ISSUE TITLE
systemd for centos 7

### ISSUE THREAD

**Issue by robertlabrie** [test-kitchen/kitchen-docker#268]
According to the readme for the image, you can run systemd in a centos 7 docker container now.
https://hub.docker.com/_/centos/

Any chance to have this added to `build_dockerfile`? `service` resources fail b/c of the lack of systemd and I'm having to use vagrant driver when porting cookbooks to 7

**Comment by coderanger** [comment]
I mean there isn't anything to add. You can configure this today, I just don't really document it because things keep changing. It would be nice if it was supported out of the box, but I haven't had the cycles.

**Comment by robertlabrie** [comment]
How do I configure it today without rolling my own custom Dockerfile?

Will you accept a PR?

**Comment by coderanger** [comment]
You'll either need a bunch of `provision_command`s or a custom Dockerfile template. Set the `run_command` to launch systemd and make sure you set things up to launch sshd somehow. That last part is the annoying one, and is why this works better with kitchen-dokken since it isn't reliant on SSH for the transport. As mentioned on other tickets, I want to do a similar thing here and make a transport that uses `docker exec` but it's hard to work out how best to do that since file transfers are currently via scp/sftp.

**Comment by robertlabrie** [comment]
Old issue I know, but here is a .kitchen.yml that works for centos 6 and centos 7 (with systemd)

- privileged because apparently the mac needs it for cgroups
- disabling pam was necessary to let kitchen login

make init the entrypoint and it starts the sshd
```
---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero

platforms:
  - name: centos-7
    driver_config:
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
  - name: centos-6
    driver:
      disable_upstart: false
      run_command: /sbin/init
suites:
  - name: default
    run_list:
      - recipe[example::default]
    attributes:
