### ISSUE TITLE
Inspec's port should be_listening does not work with kitchen-docker

### ISSUE THREAD

**Issue by AndKiel** [test-kitchen/kitchen-docker#303]
I'm currently learning chef basics and was doing the tracks from their site. I wanted to use docker instead of vagrant. Tests for port listening and mysql command were not passing at all when using docker driver. After switching to vagrant everything was fine. Something definitely is amiss (and there are probably more broken things than that).

.kitchen.yml and recipe can be found here:
https://learn.chef.io/modules/create-a-web-app-cookbook/ubuntu/virtualbox/configure-mysql#/

**Comment by coderanger** [comment]
This usually means your Docker base image doesn't contain the required networking tools. Please include your actual kitchen.yml since I'm guessing you changed more than just the driver. The `ubuntu:14.04` image does include `ss`, but if you tried to bump up to 18.04 it looks like that no longer includes either `ss` or `netstat` so it needs some tweaking.

**Comment by AndKiel** [comment]
I changed only driver's name to docker and removed driver's network as I didn't see it in kitchen-docker's readme. Everything else I left as it was.

**Comment by coderanger** [comment]
I would expect 14.04 to work, but `kitchen login` and check to see what commands are available. https://github.com/inspec/inspec/blob/7de898a4f9882d8ca259020935671f0bea75fa6b/lib/resources/port.rb#L385-L421 is the relevant code in InSpec so you can try those commands manually and see what part isn't working. Going to close this since other than maybe some problems with the ubuntu:18.04 image that need to be addressed, this does work overall.

**Comment by AndKiel** [comment]
"expect to work" != "is working"
Both ss and netstat are available. It seems that mysql is not starting inside the docker container (but it starts inside vagrant's ubuntu 14.04). I'll stick to testing on vagrant then.
