### ISSUE TITLE
new ubuntu doesn't generate en_US.UTF-8 locale

### ISSUE THREAD

**Issue by spheromak** [test-kitchen/kitchen-docker#35]
I hit an issue with some encoding, and noticed this when i rebuild all docker/kitchen boxes:

```
$ kitchen login no-bag-ubuntu-1204
kitchen@-------'s password:
/usr/bin/xauth:  file /home/kitchen/.Xauthority does not exist
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

Resolved it by running:

```
 $ sudo locale-gen en_US.UTF-8 
```

on the container.

**Comment by miketheman** [comment]
Just commenting on this as I ran into this very painfully recently.

The locale-gen command does _not_ enforce encoding, rather it compiles the locale and makes it available to be set via envvars. We had to implement #36 in our internal image, so that any process looking to `export LANG=en_us.UTF8` can do so.

**Comment by damm** [comment]
@miketheman yep it's a super minimal image; the installer sets up many files and makes `/etc/default/locale` correct for example.

It is a language agnostic minimal image.  Only the `C` locale is included so lots of people modify the base image now.

[damm/ubuntu](https://github.com/damm/docker-ubuntu) is my base image.  I guess I should fix the locale too :)
