### ISSUE TITLE
kitchen-docker does not properly detect Docker CLI tool on Ubuntu 14.04

### ISSUE THREAD

**Issue by misheska** [test-kitchen/kitchen-docker#54]
The Docker CLI tool is called `docker.io` in the new Ubuntu 14.04 Docker package.  When I try using the `kitchen-docker` plugin on Ubuntu 14.04, I get the following error because it is looking for `docker` instead of `docker.io`:

```
kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: You must first install the Docker CLI tool     http://www.docker.io/gettingstarted/
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by marzzz21** [comment]
use_sudo: false worked for me but I don't know why . . . anyone can explain?

**Comment by rkgade** [comment]
@marzzz21 That's because by default on Ubuntu installation, docker is run under sudo until you add your user to docker group. 

However, kitchen doesn't know that, hence by default, to use docker, kitchen tries to run docker as sudo. 
Now if you don't run kitchen as sudo(like sudo kitchen list), then it cannot run docker as sudo, hence it throws an error.

When you put use_sudo:false, then kitchen tries to run docker without sudo and if you have configured dokcer to run with your user, kitchen will run just fine!

**Comment by marzzz21** [comment]
@rkgade I see, that explains it. Thanks for taking the time to elaborate.

**Comment by nqb** [comment]
For the record, I got same issue under Debian 9 with a user able to run `docker` commands and a local socket. My user is member of `sudo` and `docker` group and I specify `use_sudo: false` in my `kitchen.yml`.

After adding `NOPASSWD` in my sudoers file:
```
%sudo   ALL=(ALL:ALL) NOPASSWD:ALL
```
it works.
